"""Ass

Revision ID: 003f2025c5b8
Revises: c81e16c929dd
Create Date: 2026-04-10 20:53:54.827386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003f2025c5b8'
down_revision: Union[str, Sequence[str], None] = 'c81e16c929dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assessments_category_id_fkey'), 'assessments', type_='foreignkey')
    op.drop_column('assessments', 'category_id')
    op.add_column('categories', sa.Column('assessment_type_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('fk_categories_assessment'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'assessment_types', ['assessment_type_id'], ['assessment_type_id'])
    op.drop_column('categories', 'assessment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('fk_categories_assessment'), 'categories', 'assessments', ['assessment_id'], ['assessment_id'], ondelete='CASCADE')
    op.drop_column('categories', 'assessment_type_id')
    op.add_column('assessments', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('assessments_category_id_fkey'), 'assessments', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
