"""K

Revision ID: 041c834cd075
Revises: 003f2025c5b8
Create Date: 2026-04-10 23:06:13.955481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041c834cd075'
down_revision: Union[str, Sequence[str], None] = '003f2025c5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_details')
    op.add_column('assessments', sa.Column('assessment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'assessment_date')
    op.create_table('assessment_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('obtained_marks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_details', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], name=op.f('assessment_details_assessment_id_fkey')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('assessment_details_category_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('assessment_details_pkey'))
    )
    # ### end Alembic commands ###
