"""Assesments

Revision ID: 16195d9d1cec
Revises: 4476ab64d7c6
Create Date: 2026-04-10 15:31:48.702610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16195d9d1cec'
down_revision: Union[str, Sequence[str], None] = '4476ab64d7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assessments', 'categories', ['category_id'], ['id'])
    op.drop_constraint(op.f('categories_assessment_type_id_fkey'), 'categories', type_='foreignkey')
    op.drop_column('categories', 'assessment_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('assessment_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('categories_assessment_type_id_fkey'), 'categories', 'assessment_types', ['assessment_type_id'], ['assessment_type_id'])
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_column('assessments', 'category_id')
    # ### end Alembic commands ###
