"""initial migration

Revision ID: 2717e709085d
Revises: 
Create Date: 2026-03-25 22:23:19.785166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2717e709085d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_assessments',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('pass_mark', sa.Integer(), nullable=True),
    sa.Column('total_mark', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=255), nullable=True),
    sa.Column('Created_At', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('Updated_At', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_table('exam_section',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('exam_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('usertype', sa.String(length=20), nullable=True),
    sa.Column('Created_At', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('Updated_At', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('exam_attempts',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['exam_assessments.assessment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['exam_user.user_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_table('exam_questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('assessments_id', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.String(length=255), nullable=True),
    sa.Column('question_text', sa.JSON(), nullable=True),
    sa.Column('question_section', sa.String(length=255), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('correct_option', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['assessments_id'], ['exam_assessments.assessment_id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['exam_section.section_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('exam_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('is_skipped', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.attempt_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('exam_options',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('option_label', sa.CHAR(length=1), nullable=True),
    sa.Column('option_text', sa.TEXT(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.question_id'], ),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.drop_table('pay_email')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('admin', 'student', name='user_role'), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'deleted', name='user_activity'), autoincrement=False, nullable=True),
    sa.Column('is2FA', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('pay_email',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('from_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('upi_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'deleted', name='user_activity'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['users.user_id'], name=op.f('pay_email_from_id_fkey')),
    sa.ForeignKeyConstraint(['to_id'], ['users.user_id'], name=op.f('pay_email_to_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pay_email_pkey')),
    sa.UniqueConstraint('invoice_no', name=op.f('pay_email_invoice_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('exam_options')
    op.drop_table('exam_answers')
    op.drop_table('exam_questions')
    op.drop_table('exam_attempts')
    op.drop_table('exam_user')
    op.drop_table('exam_section')
    op.drop_table('exam_assessments')
    # ### end Alembic commands ###
