"""Assesments

Revision ID: 4476ab64d7c6
Revises: db63bde4a831
Create Date: 2026-04-10 15:24:45.241000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4476ab64d7c6'
down_revision: Union[str, Sequence[str], None] = 'db63bde4a831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assessment_types_assessment_id_fkey'), 'assessment_types', type_='foreignkey')
    op.drop_column('assessment_types', 'assessment_id')
    op.add_column('assessments', sa.Column('assessment_id', sa.Integer(), nullable=False))
    op.add_column('assessments', sa.Column('assessment_type_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_assessments_Assessment_id'), table_name='assessments')
    op.create_index(op.f('ix_assessments_assessment_id'), 'assessments', ['assessment_id'], unique=False)
    op.create_foreign_key(None, 'assessments', 'assessment_types', ['assessment_type_id'], ['assessment_type_id'])
    op.drop_column('assessments', 'Assessment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('Assessment_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_index(op.f('ix_assessments_assessment_id'), table_name='assessments')
    op.create_index(op.f('ix_assessments_Assessment_id'), 'assessments', ['Assessment_id'], unique=False)
    op.drop_column('assessments', 'assessment_type_id')
    op.drop_column('assessments', 'assessment_id')
    op.add_column('assessment_types', sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('assessment_types_assessment_id_fkey'), 'assessment_types', 'assessments', ['assessment_id'], ['Assessment_id'])
    # ### end Alembic commands ###
