"""add bank details

Revision ID: 4dab7c692869
Revises: f37f4fc308ba
Create Date: 2026-03-27 22:38:04.605243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dab7c692869'
down_revision: Union[str, Sequence[str], None] = 'f37f4fc308ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay_email', sa.Column('account_name', sa.String(), nullable=True))
    op.add_column('pay_email', sa.Column('account_no', sa.String(), nullable=True))
    op.add_column('pay_email', sa.Column('ifsc', sa.String(), nullable=True))
    op.add_column('pay_email', sa.Column('bank_name', sa.String(), nullable=True))
    op.drop_column('pay_email', 'upi_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('pay_email', sa.Column('upi_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pay_email', 'bank_name')
    op.drop_column('pay_email', 'ifsc')
    op.drop_column('pay_email', 'account_no')
    op.drop_column('pay_email', 'account_name')
    # ### end Alembic commands ###
