"""payemail

Revision ID: 6c011d885fdd
Revises: 932ee74f2921
Create Date: 2026-03-30 14:08:02.605331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c011d885fdd'
down_revision: Union[str, Sequence[str], None] = '932ee74f2921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pay_email_invoice_no_key'), 'pay_email', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('pay_email_invoice_no_key'), 'pay_email', ['invoice_no'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
