"""task

Revision ID: 753931ccc1dd
Revises: 2cf0d9b76634
Create Date: 2026-04-03 17:35:17.852869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '753931ccc1dd'
down_revision: Union[str, Sequence[str], None] = '2cf0d9b76634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_testcases_id'), table_name='program_testcases')
    op.drop_table('program_testcases')
    op.drop_index(op.f('ix_program_submissions_id'), table_name='program_submissions')
    op.drop_table('program_submissions')
    op.drop_index(op.f('ix_program_questions_id'), table_name='program_questions')
    op.drop_table('program_questions')
    op.drop_constraint(op.f('coding_questions_question_id_fkey'), 'coding_questions', type_='foreignkey')
    op.create_foreign_key(None, 'coding_questions', 'exam_questions', ['question_id'], ['question_id'])
    op.drop_constraint(op.f('coding_submissions_question_id_fkey'), 'coding_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'coding_submissions', 'exam_questions', ['question_id'], ['question_id'])
    op.alter_column('exam_user', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('exam_user', 'email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
    #op.create_unique_constraint(None, 'exam_user', ['email'])
    #op.create_unique_constraint(None, 'exam_user', ['password'])
    op.add_column('users', sa.Column('current_task_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_task_id')
    op.drop_constraint(None, 'exam_user', type_='unique')
    op.drop_constraint(None, 'exam_user', type_='unique')
    op.alter_column('exam_user', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('exam_user', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_constraint(None, 'coding_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('coding_submissions_question_id_fkey'), 'coding_submissions', 'exam_questions', ['question_id'], ['question_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'coding_questions', type_='foreignkey')
    op.create_foreign_key(op.f('coding_questions_question_id_fkey'), 'coding_questions', 'exam_questions', ['question_id'], ['question_id'], ondelete='CASCADE')
    op.create_table('program_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('program_questions_pkey'))
    )
    op.create_index(op.f('ix_program_questions_id'), 'program_questions', ['id'], unique=False)
    op.create_table('program_submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('program_submissions_pkey'))
    )
    op.create_index(op.f('ix_program_submissions_id'), 'program_submissions', ['id'], unique=False)
    op.create_table('program_testcases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('input_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expected_output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['program_questions.id'], name=op.f('program_testcases_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('program_testcases_pkey'))
    )
    op.create_index(op.f('ix_program_testcases_id'), 'program_testcases', ['id'], unique=False)
    # ### end Alembic commands ###
