"""initial migration

Revision ID: 7b9a96b6b3a7
Revises: 3575a36a37aa
Create Date: 2026-03-26 12:00:59.835708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9a96b6b3a7'
down_revision: Union[str, Sequence[str], None] = '3575a36a37aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exam_attempts_user_id_fkey'), 'exam_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'exam_attempts', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('exam_attempts_user_id_fkey'), 'exam_attempts', 'exam_user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
