"""attempts change

Revision ID: 8df271a08ae3
Revises: 103dce11bab7
Create Date: 2026-03-28 14:30:32.468747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df271a08ae3'
down_revision: Union[str, Sequence[str], None] = '103dce11bab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_attempts', sa.Column('aptitude_correct', sa.Integer(), nullable=True))
    op.add_column('exam_attempts', sa.Column('aptitude_wrong', sa.Integer(), nullable=True))
    op.add_column('exam_attempts', sa.Column('aptitude_skipped', sa.Integer(), nullable=True))
    op.add_column('exam_attempts', sa.Column('technical_correct', sa.Integer(), nullable=True))
    op.add_column('exam_attempts', sa.Column('technical_wrong', sa.Integer(), nullable=True))
    op.add_column('exam_attempts', sa.Column('technical_skipped', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_attempts', 'technical_skipped')
    op.drop_column('exam_attempts', 'technical_wrong')
    op.drop_column('exam_attempts', 'technical_correct')
    op.drop_column('exam_attempts', 'aptitude_skipped')
    op.drop_column('exam_attempts', 'aptitude_wrong')
    op.drop_column('exam_attempts', 'aptitude_correct')
    # ### end Alembic commands ###
