"""exam user

Revision ID: 9d6b26dd8b7d
Revises: 8e60aba645ba
Create Date: 2026-03-30 01:19:30.710200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6b26dd8b7d'
down_revision: Union[str, Sequence[str], None] = '8e60aba645ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_user', sa.Column('is_logged_in', sa.Boolean(), nullable=True))
    op.add_column('exam_user', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_user', 'last_login')
    op.drop_column('exam_user', 'is_logged_in')
    # ### end Alembic commands ###
