"""added status to usr table

Revision ID: 9e803a9f72fa
Revises: 27c6be4079d9
Create Date: 2026-03-25 13:37:28.815396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e803a9f72fa'
down_revision: Union[str, Sequence[str], None] = '27c6be4079d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_activity_enum = sa.Enum('active', 'inactive', 'deleted', name='user_activity')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_activity_enum.create(op.get_bind(), checkfirst=True)

    # ✅ Then add column
    op.add_column(
        'users',
        sa.Column('status', user_activity_enum, nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
