"""Assesment

Revision ID: c81e16c929dd
Revises: 16195d9d1cec
Create Date: 2026-04-10 16:29:06.356381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c81e16c929dd'
down_revision: Union[str, Sequence[str], None] = '16195d9d1cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('obtained_marks', sa.Integer(), nullable=True))
    op.drop_column('assessments', 'total_marks')
    op.drop_column('categories', 'obtained_marks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('obtained_marks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('total_marks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('assessments', 'obtained_marks')
    # ### end Alembic commands ###
