"""msg table after nullable

Revision ID: cbb2a7534eca
Revises: e6d759ee01c8
Create Date: 2026-04-04 13:48:32.183387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb2a7534eca'
down_revision: Union[str, Sequence[str], None] = 'e6d759ee01c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('ConversationID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.Column('IsGroup', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.Column('CreatedOn', sa.DateTime(), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=True),
    sa.Column('updatedOn', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ConversationID')
    )
    op.create_table('conversationmember',
    sa.Column('ConversationID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('JoinedAt', sa.DateTime(), nullable=True),
    sa.Column('Role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('CreatedOn', sa.DateTime(), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=True),
    sa.Column('updatedOn', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ConversationID'], ['conversation.ConversationID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ConversationID', 'UserID')
    )
    op.create_table('message',
    sa.Column('MessageID', sa.Integer(), nullable=False),
    sa.Column('ConversationID', sa.Integer(), nullable=False),
    sa.Column('SenderID', sa.Integer(), nullable=False),
    sa.Column('Content', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('CreatedOn', sa.DateTime(), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('updatedOn', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ConversationID'], ['conversation.ConversationID'], ),
    sa.ForeignKeyConstraint(['SenderID'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('MessageID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('conversationmember')
    op.drop_table('conversation')
    # ### end Alembic commands ###
