"""usr table

Revision ID: d084f0a8690a
Revises: 
Create Date: 2026-03-26 10:13:38.557673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd084f0a8690a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('admin', 'student', name='user_role'), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'deleted', name='user_activity'), nullable=True),
    sa.Column('is2FA', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pay_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(), nullable=True),
    sa.Column('from_id', sa.Integer(), nullable=True),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('email_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('due_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('upi_id', sa.String(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'deleted', name='user_activity'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.drop_table('exam_questions')
    op.drop_table('exam_assessments')
    op.drop_table('exam_options')
    op.drop_table('exam_answers')
    op.drop_table('exam_attempts')
    op.drop_table('exam_user')
    op.drop_table('exam_section')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_section',
    sa.Column('section_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('section_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('section_id', name=op.f('exam_section_pkey'))
    )
    op.create_table('exam_user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('usertype', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('Created_At', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('Updated_At', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('exam_user_pkey')),
    sa.UniqueConstraint('username', name=op.f('exam_user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('exam_attempts',
    sa.Column('attempt_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['exam_assessments.assessment_id'], name=op.f('exam_attempts_assessment_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['exam_user.user_id'], name=op.f('exam_attempts_user_id_fkey')),
    sa.PrimaryKeyConstraint('attempt_id', name=op.f('exam_attempts_pkey'))
    )
    op.create_table('exam_answers',
    sa.Column('answer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('selected_option_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_skipped', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.attempt_id'], name=op.f('exam_answers_attempt_id_fkey')),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.question_id'], name=op.f('exam_answers_question_id_fkey')),
    sa.PrimaryKeyConstraint('answer_id', name=op.f('exam_answers_pkey'))
    )
    op.create_table('exam_options',
    sa.Column('option_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('option_label', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('option_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.question_id'], name=op.f('exam_options_question_id_fkey')),
    sa.PrimaryKeyConstraint('option_id', name=op.f('exam_options_pkey'))
    )
    op.create_table('exam_assessments',
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pass_mark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_mark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Created_At', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('Updated_At', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('assessment_id', name=op.f('exam_assessments_pkey'))
    )
    op.create_table('exam_questions',
    sa.Column('question_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assessments_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('question_text', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('question_section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correct_option', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessments_id'], ['exam_assessments.assessment_id'], name=op.f('exam_questions_assessments_id_fkey')),
    sa.ForeignKeyConstraint(['section_id'], ['exam_section.section_id'], name=op.f('exam_questions_section_id_fkey')),
    sa.PrimaryKeyConstraint('question_id', name=op.f('exam_questions_pkey'))
    )
    op.drop_table('pay_email')
    op.drop_table('users')
    # ### end Alembic commands ###
