"""Assesments

Revision ID: db63bde4a831
Revises: f75e49efc46d
Create Date: 2026-04-10 15:04:36.964652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db63bde4a831'
down_revision: Union[str, Sequence[str], None] = 'f75e49efc46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('Assessment_id', sa.Integer(), nullable=False),
    sa.Column('intern_id', sa.Integer(), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('task_details', sa.String(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['intern_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('Assessment_id')
    )
    op.create_index(op.f('ix_assessments_Assessment_id'), 'assessments', ['Assessment_id'], unique=False)
    op.create_table('assessment_types',
    sa.Column('assessment_type_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('assessment_name', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.Assessment_id'], ),
    sa.PrimaryKeyConstraint('assessment_type_id')
    )
    op.create_index(op.f('ix_assessment_types_assessment_type_id'), 'assessment_types', ['assessment_type_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_type_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('obtained_marks', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_type_id'], ['assessment_types.assessment_type_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_assessment_types_assessment_type_id'), table_name='assessment_types')
    op.drop_table('assessment_types')
    op.drop_index(op.f('ix_assessments_Assessment_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
