"""msg table

Revision ID: e6d759ee01c8
Revises: 60bd129b2e73
Create Date: 2026-04-04 13:47:19.568881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d759ee01c8'
down_revision: Union[str, Sequence[str], None] = '60bd129b2e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'batch',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'batch',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
